labels:
  subsystem: submission-moderation
  service_group: backend

scaling:
  worker_replicas: "3"
  api_replicas: "3"

redis:
  host: task-queue-development
  port: 6379
namespace: development
image:
  tag: "0.0"

deployment:
  name: compiler
service:
  name: compiler

redis:
  url: changeme

vault:
  host: changeme
  port: changeme
  role: compiler
  credential: compiler

s3:
  submission:
    bucket: compiler-submission
    region: us-east-1
  bucket: compiler-submission
  region: us-east-1


converter.image: arxiv/converter:0.9

loglevel: 10

filemanager:
  override: false
  host: "arxiv.org"
  port: "443"
  proto: "http"
  path: "/"
  content_path: "/src/{source_id}"
  verify_checksum: "0"
  status_endpoint: ""


ingress:
  host: "development.arxiv.org"
  path: "/compiler"
