language: python
sudo: required
services:
  - docker
cache: pip
env:
  - MIN_SCORE=9
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run openapi-spec-validator schema/openapi.yaml
  - pipenv run nose2 --with-coverage
