openapi: "3.0.0"
info:
  version: "0.1"
  title: "arXiv Compliler Service"
  contact:
    name: "arXiv API Team"
    email: nextgen@arxiv.org
  license:
    name: MIT

components:
  parameters:
    upload_id:
      name: upload_id
      in: path
      description: The upload workspace ID.
      required: true
      schema:
        type: integer
    format:
      name: format
      in: path
      description: The compilation output format.
      required: true
      schema:
        type: string

paths:
  /status:
    get:
      operationId: getServiceStatus
      summary: |
        Get information about the current status of file management service.
      responses:
        '200':
          description: OK
        '503':
          description: Service Unavailable

  /{upload_id}:
    parameters:
    - $ref: '#/components/parameters/upload_id'
    get:
      operationId: getCompilationInfo
      description: Return information about all compilations requested for the upload workspace.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'resources/compilationInfo.json'


  /{upload_id}/{format}:
    parameters:
    - $ref: '#/components/parameters/upload_id'
    - $ref: '#/components/parameters/format'
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'resources/CompilationProduct.json'
        '303':
          description: Redirect to getTaskStatus for the compilation.
        '404':
          description: No compilation has been requested.
    post:
      operationId: requestCompilation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'resources/requestCompilation.json'
      responses:
        '202':
          description: Accepted for compilation.
          headers:
            Location:
              description: The URL for the compilation task.
              schema:
                type: string

  /{upload_id}/{format}/log:
    parameters:
    - $ref: '#/components/parameters/upload_id'
    - $ref: '#/components/parameters/format'
    get:
      operationId: getCompilationLog
      responses:
        '200':
          description: OK

  /{upload_id}/{format}/product:
    parameters:
    - $ref: '#/components/parameters/upload_id'
    - $ref: '#/components/parameters/format'
    get:
      operationId: getCompilationProduct
      responses:
        '200':
          description: OK

  /task/{uuid}:
    parameters:
    - name: uuid
      in: path
      description: The task's UUID.
      required: true
      schema:
        type: string
    get:
      operationId: getTaskStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'resources/CompilationProduct.json'
        '301':
          description: With the task complete, redirect to the completed object.
          headers:
            Location:
              description: The URL for the successfully completed object.
              schema:
                type: string
