openapi: "3.0.0"
info:
  version: "0.1"
  title: "arXiv Compliler Service"
  contact:
    name: "arXiv API Team"
    email: nextgen@arxiv.org
  license:
    name: MIT

paths:
  /status:
    get:
      operationId: getServiceStatus
      summary: |
        Get information about the current status of file management service.
      responses:
        '200':
          description: OK
        '503':
          description: Service Unavailable

  /{upload_id}:
    get:
      operationId: getCompilationInfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'resources/compilationInfo.json'


  /{upload_id}/{format}:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'resources/CompilationProduct.json'
        '303': 
          description: Redirect to getTaskStatus for the compilation.
        '404': 
          description: No compilation has been requested.
    post:
      operationId: requestCompilation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'resources/requestCompilation.json'
      responses:
        '202': 
          description: Accepted for compilation. Location header defines URL.
          # TODO: Figure out how to properly spec Location header

  /{upload_id}/{format}/log:
    get:
      operationId: getCompilationLog
  
  /{upload_id}/{format}/product:
    get:
      operationId: getCompilationProduct

  /task/{uuid}:
    get:
      operationId: getTaskStatus
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'resources/CompilationProduct.json'
				'301':
          description: Redirect to /{upload_id}/{format}
